#region License
// ImportModel.cs is part of ReadingTool.Site
// 
// ReadingTool.Site is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// ReadingTool.Site is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with ReadingTool.Site. If not, see <http://www.gnu.org/licenses/>.
// 
// Copyright (C) 2013 Travis Watt
#endregion

using System.ComponentModel.DataAnnotations;
using System.Web;
using ReadingTool.Site.Attributes;

namespace ReadingTool.Site.Models.Account
{
    public class ImportModel
    {
        [Display(Name = "Test Mode?")]
        [Tip("Doesn't actually try save your data, just makes an attempt to parse the data for errors.")]
        public bool TestMode { get; set; }
        
        [Tip("The JSON file, or zipped version, containing your LWT data. Generated by the jsonexport.php script.")]
        public HttpPostedFileBase File { get; set; }
    }
}