//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingTool.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XsltResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XsltResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadingTool.Services.XsltResource", typeof(XsltResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:template match=&quot;/root&quot;&gt;
        ///    &lt;xsl:apply-templates select=&quot;link&quot;/&gt;
        ///    &lt;xsl:apply-templates select=&quot;stats&quot;/&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:template match=&quot;link&quot;&gt;
        ///    &lt;xsl:apply-templates select=&quot;p[@side=&apos;first&apos;]&quot;/&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:template match=&quot;p[@side=&apos;first&apos;]&quot;&gt;
        ///    &lt;p&gt;
        ///      &lt;xsl:attribute name=&quot;dir&quot;&gt;
        ///        &lt;xsl:value-of select=&quot;@dir&quot; /&gt;
        ///      &lt;/xsl:attribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;text&quot; indent=&quot;no&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
        ///
        ///  &lt;xsl:template match=&quot;/root&quot;&gt;
        ///    &lt;xsl:text&gt;\documentclass[12pt]{article}
        ///
        ///&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\usepackage[papersize={108mm,144mm},margin=2mm]{geometry}
        ///
        ///&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\usepackage[utf8]{inputenc}
        ///
        ///&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\usepackage{perpage}
        ///
        ///&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\MakePerPage{fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Read_Latex {
            get {
                return ResourceManager.GetString("Read_Latex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:template match=&quot;/root&quot;&gt;
        ///    &lt;table&gt;
        ///      &lt;xsl:apply-templates select=&quot;link&quot;/&gt;
        ///    &lt;/table&gt;
        ///    &lt;xsl:apply-templates select=&quot;stats&quot;/&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:template match=&quot;link&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;xsl:apply-templates select=&quot;p&quot;/&gt;
        ///    &lt;/tr&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:template match=&quot;p[@side=&apos;first&apos;]&quot;&gt;
        ///    &lt;td&gt;
        ///      &lt;xsl:attribute name=&quot;class&quot;&gt;f&lt;/xsl:attribute&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Read_Parallel {
            get {
                return ResourceManager.GetString("Read_Parallel", resourceCulture);
            }
        }
    }
}
